# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://youdingtian.com'
baseurl: ''
title: 'YOUDINGTIAN'
description: '有顶天正版模玩专注奥特曼周边'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i1/2710706468/O1CN01NPHDHL1xeOUiOWCoa_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: 首页
  url: /
- title: 关于
  url: /about/
- title: 联系
  url: /contact/
- title: 博客
  url: /blog/

# Footer nav
navigation_footer:
- title: 返回顶部↑Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 博客
    output: true
    description: "请你添加我们的微信ID：320 297 252 留意我们朋友圈的更新"
    feature_text: 
    feature_image: "https://img.alicdn.com/imgextra/i1/2710706468/O1CN01EricuZ1xeOUgXsY8v_!!2710706468.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
